#!/bin/bash

# Generates thumbs

rm -rf .thumbs/
mkdir .thumbs

find \( -iname "*.png" -or -iname "*.jpg" -or -iname "*.jpeg" \) -exec bash -c 'mogrify -path .thumbs/ -auto-orient -thumbnail 128x128 -quality 90% "{}" &' \;
